---
application:
  name: "studia-bot"
  project: "studia_bot"
  organization: "QoveryCommunity"
  cpu: 1
  ram: 1024MB
routers:
- name: "main-studia-bot"
  routes:
  - application_name: "studia-bot"
    paths:
    - "/*"
